name: VSCode Auto Release
on:
  schedule:
    - cron: 0 0 15 * *
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: |
            args: [--frozen-lockfile, --strict-peer-dependencies]
      - run: pnpm i vscode-latest@npm:@types/vscode@latest
      - run: pnpm i esbuild-latest@npm:esbuild@latest
      - id: shouldContinue
        run: pnpx tsm scripts/checkNeedsPublish.ts
      - run: echo $OUTPUT
        env:
          OUTPUT: ${{ steps.shouldContinue.outputs.shouldContinue }}
      - run: pnpx zardoy-release vscode-extension --auto-update
        if: steps.shouldContinue.outputs.shouldContinue == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
